version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: './docker/${VUE_APP_ENV}/dockerfile'
    container_name: sgp_front
    ports:
      - '16900:16900'
    volumes:
      - ./:/app